digraph "unitGraph" {
    "r0 = \"123456789\""
    "$r1 = <com.ethjava.AccountManager: org.web3j.protocol.admin.Admin admin>"
    "$r2 = interfaceinvoke $r1.<org.web3j.protocol.admin.Admin: org.web3j.protocol.core.Request personalNewAccount(java.lang.String)>(r0)"
    "$r3 = virtualinvoke $r2.<org.web3j.protocol.core.Request: org.web3j.protocol.core.Response send()>()"
    "r11 = (org.web3j.protocol.admin.methods.response.NewAccountIdentifier) $r3"
    "r4 = virtualinvoke r11.<org.web3j.protocol.admin.methods.response.NewAccountIdentifier: java.lang.String getAccountId()>()"
    "$r6 = <java.lang.System: java.io.PrintStream out>"
    "$r5 = new java.lang.StringBuilder"
    "specialinvoke $r5.<java.lang.StringBuilder: void <init>()>()"
    "$r7 = virtualinvoke $r5.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"new account address \")"
    "$r8 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r4)"
    "$r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.String toString()>()"
    "virtualinvoke $r6.<java.io.PrintStream: void println(java.lang.String)>($r9)"
    "goto [?= return]"
    "$r10 := @caughtexception"
    "r12 = $r10"
    "virtualinvoke r12.<java.io.IOException: void printStackTrace()>()"
    "return"
    "r0 = \"123456789\""->"$r1 = <com.ethjava.AccountManager: org.web3j.protocol.admin.Admin admin>";
    "r0 = \"123456789\""->"$r10 := @caughtexception";
    "$r1 = <com.ethjava.AccountManager: org.web3j.protocol.admin.Admin admin>"->"$r2 = interfaceinvoke $r1.<org.web3j.protocol.admin.Admin: org.web3j.protocol.core.Request personalNewAccount(java.lang.String)>(r0)";
    "$r1 = <com.ethjava.AccountManager: org.web3j.protocol.admin.Admin admin>"->"$r10 := @caughtexception";
    "$r2 = interfaceinvoke $r1.<org.web3j.protocol.admin.Admin: org.web3j.protocol.core.Request personalNewAccount(java.lang.String)>(r0)"->"$r3 = virtualinvoke $r2.<org.web3j.protocol.core.Request: org.web3j.protocol.core.Response send()>()";
    "$r2 = interfaceinvoke $r1.<org.web3j.protocol.admin.Admin: org.web3j.protocol.core.Request personalNewAccount(java.lang.String)>(r0)"->"$r10 := @caughtexception";
    "$r3 = virtualinvoke $r2.<org.web3j.protocol.core.Request: org.web3j.protocol.core.Response send()>()"->"r11 = (org.web3j.protocol.admin.methods.response.NewAccountIdentifier) $r3";
    "$r3 = virtualinvoke $r2.<org.web3j.protocol.core.Request: org.web3j.protocol.core.Response send()>()"->"$r10 := @caughtexception";
    "r11 = (org.web3j.protocol.admin.methods.response.NewAccountIdentifier) $r3"->"r4 = virtualinvoke r11.<org.web3j.protocol.admin.methods.response.NewAccountIdentifier: java.lang.String getAccountId()>()";
    "r11 = (org.web3j.protocol.admin.methods.response.NewAccountIdentifier) $r3"->"$r10 := @caughtexception";
    "r4 = virtualinvoke r11.<org.web3j.protocol.admin.methods.response.NewAccountIdentifier: java.lang.String getAccountId()>()"->"$r6 = <java.lang.System: java.io.PrintStream out>";
    "r4 = virtualinvoke r11.<org.web3j.protocol.admin.methods.response.NewAccountIdentifier: java.lang.String getAccountId()>()"->"$r10 := @caughtexception";
    "$r6 = <java.lang.System: java.io.PrintStream out>"->"$r5 = new java.lang.StringBuilder";
    "$r6 = <java.lang.System: java.io.PrintStream out>"->"$r10 := @caughtexception";
    "$r5 = new java.lang.StringBuilder"->"specialinvoke $r5.<java.lang.StringBuilder: void <init>()>()";
    "$r5 = new java.lang.StringBuilder"->"$r10 := @caughtexception";
    "specialinvoke $r5.<java.lang.StringBuilder: void <init>()>()"->"$r7 = virtualinvoke $r5.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"new account address \")";
    "specialinvoke $r5.<java.lang.StringBuilder: void <init>()>()"->"$r10 := @caughtexception";
    "$r7 = virtualinvoke $r5.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"new account address \")"->"$r8 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r4)";
    "$r7 = virtualinvoke $r5.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"new account address \")"->"$r10 := @caughtexception";
    "$r8 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r4)"->"$r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.String toString()>()";
    "$r8 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r4)"->"$r10 := @caughtexception";
    "$r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.String toString()>()"->"virtualinvoke $r6.<java.io.PrintStream: void println(java.lang.String)>($r9)";
    "$r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.String toString()>()"->"$r10 := @caughtexception";
    "virtualinvoke $r6.<java.io.PrintStream: void println(java.lang.String)>($r9)"->"goto [?= return]";
    "virtualinvoke $r6.<java.io.PrintStream: void println(java.lang.String)>($r9)"->"$r10 := @caughtexception";
    "goto [?= return]"->"return";
    "$r10 := @caughtexception"->"r12 = $r10";
    "r12 = $r10"->"virtualinvoke r12.<java.io.IOException: void printStackTrace()>()";
    "virtualinvoke r12.<java.io.IOException: void printStackTrace()>()"->"return";
}
