digraph "unitGraph" {
    "Block 0:
[preds: ] [succs: 1 15 ]
r6 := @parameter0: java.lang.String[];
"
    "Block 1:
[preds: 0 ] [succs: 2 15 ]
i1 = 0;
"
    "Block 2:
[preds: 1 ] [succs: 5 15 ]
goto [?= (branch)];
"
    "Block 3:
[preds: 5 ] [succs: 4 15 ]
staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: long m1()>();
"
    "Block 4:
[preds: 3 ] [succs: 5 15 ]
i1 = i1 + 1;
"
    "Block 5:
[preds: 2 4 ] [succs: 6 3 15 ]
if i1 < 20000 goto staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: long m1()>();
"
    "Block 6:
[preds: 5 ] [succs: 7 15 ]
$r0 = new compiler.profiling.TestMethodHandleInvokesIntrinsic;
"
    "Block 7:
[preds: 6 ] [succs: 8 15 ]
specialinvoke $r0.<compiler.profiling.TestMethodHandleInvokesIntrinsic: void <init>()>();
"
    "Block 8:
[preds: 7 ] [succs: 9 15 ]
r7 = $r0;
"
    "Block 9:
[preds: 8 ] [succs: 10 15 ]
i2 = 0;
"
    "Block 10:
[preds: 9 ] [succs: 13 15 ]
goto [?= (branch)];
"
    "Block 11:
[preds: 13 ] [succs: 12 15 ]
staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: java.lang.Class m2(java.lang.Object)>(r7);
"
    "Block 12:
[preds: 11 ] [succs: 13 15 ]
i2 = i2 + 1;
"
    "Block 13:
[preds: 10 12 ] [succs: 14 11 15 ]
if i2 < 20000 goto staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: java.lang.Class m2(java.lang.Object)>(r7);
"
    "Block 14:
[preds: 13 ] [succs: 16 ]
goto [?= $r2 = <java.lang.System: java.io.PrintStream out>];
"
    "Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
"
    "Block 16:
[preds: 14 ] [succs: ]
$r2 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r2.<java.io.PrintStream: void println(java.lang.String)>(\"TEST PASSED\");
return;
"
    "Block 0:
[preds: ] [succs: 1 15 ]
r6 := @parameter0: java.lang.String[];
"->"Block 1:
[preds: 0 ] [succs: 2 15 ]
i1 = 0;
";
    "Block 0:
[preds: ] [succs: 1 15 ]
r6 := @parameter0: java.lang.String[];
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 1:
[preds: 0 ] [succs: 2 15 ]
i1 = 0;
"->"Block 2:
[preds: 1 ] [succs: 5 15 ]
goto [?= (branch)];
";
    "Block 1:
[preds: 0 ] [succs: 2 15 ]
i1 = 0;
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 2:
[preds: 1 ] [succs: 5 15 ]
goto [?= (branch)];
"->"Block 5:
[preds: 2 4 ] [succs: 6 3 15 ]
if i1 < 20000 goto staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: long m1()>();
";
    "Block 2:
[preds: 1 ] [succs: 5 15 ]
goto [?= (branch)];
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 3:
[preds: 5 ] [succs: 4 15 ]
staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: long m1()>();
"->"Block 4:
[preds: 3 ] [succs: 5 15 ]
i1 = i1 + 1;
";
    "Block 3:
[preds: 5 ] [succs: 4 15 ]
staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: long m1()>();
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 4:
[preds: 3 ] [succs: 5 15 ]
i1 = i1 + 1;
"->"Block 5:
[preds: 2 4 ] [succs: 6 3 15 ]
if i1 < 20000 goto staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: long m1()>();
";
    "Block 4:
[preds: 3 ] [succs: 5 15 ]
i1 = i1 + 1;
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 5:
[preds: 2 4 ] [succs: 6 3 15 ]
if i1 < 20000 goto staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: long m1()>();
"->"Block 6:
[preds: 5 ] [succs: 7 15 ]
$r0 = new compiler.profiling.TestMethodHandleInvokesIntrinsic;
";
    "Block 5:
[preds: 2 4 ] [succs: 6 3 15 ]
if i1 < 20000 goto staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: long m1()>();
"->"Block 3:
[preds: 5 ] [succs: 4 15 ]
staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: long m1()>();
";
    "Block 5:
[preds: 2 4 ] [succs: 6 3 15 ]
if i1 < 20000 goto staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: long m1()>();
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 6:
[preds: 5 ] [succs: 7 15 ]
$r0 = new compiler.profiling.TestMethodHandleInvokesIntrinsic;
"->"Block 7:
[preds: 6 ] [succs: 8 15 ]
specialinvoke $r0.<compiler.profiling.TestMethodHandleInvokesIntrinsic: void <init>()>();
";
    "Block 6:
[preds: 5 ] [succs: 7 15 ]
$r0 = new compiler.profiling.TestMethodHandleInvokesIntrinsic;
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 7:
[preds: 6 ] [succs: 8 15 ]
specialinvoke $r0.<compiler.profiling.TestMethodHandleInvokesIntrinsic: void <init>()>();
"->"Block 8:
[preds: 7 ] [succs: 9 15 ]
r7 = $r0;
";
    "Block 7:
[preds: 6 ] [succs: 8 15 ]
specialinvoke $r0.<compiler.profiling.TestMethodHandleInvokesIntrinsic: void <init>()>();
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 8:
[preds: 7 ] [succs: 9 15 ]
r7 = $r0;
"->"Block 9:
[preds: 8 ] [succs: 10 15 ]
i2 = 0;
";
    "Block 8:
[preds: 7 ] [succs: 9 15 ]
r7 = $r0;
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 9:
[preds: 8 ] [succs: 10 15 ]
i2 = 0;
"->"Block 10:
[preds: 9 ] [succs: 13 15 ]
goto [?= (branch)];
";
    "Block 9:
[preds: 8 ] [succs: 10 15 ]
i2 = 0;
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 10:
[preds: 9 ] [succs: 13 15 ]
goto [?= (branch)];
"->"Block 13:
[preds: 10 12 ] [succs: 14 11 15 ]
if i2 < 20000 goto staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: java.lang.Class m2(java.lang.Object)>(r7);
";
    "Block 10:
[preds: 9 ] [succs: 13 15 ]
goto [?= (branch)];
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 11:
[preds: 13 ] [succs: 12 15 ]
staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: java.lang.Class m2(java.lang.Object)>(r7);
"->"Block 12:
[preds: 11 ] [succs: 13 15 ]
i2 = i2 + 1;
";
    "Block 11:
[preds: 13 ] [succs: 12 15 ]
staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: java.lang.Class m2(java.lang.Object)>(r7);
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 12:
[preds: 11 ] [succs: 13 15 ]
i2 = i2 + 1;
"->"Block 13:
[preds: 10 12 ] [succs: 14 11 15 ]
if i2 < 20000 goto staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: java.lang.Class m2(java.lang.Object)>(r7);
";
    "Block 12:
[preds: 11 ] [succs: 13 15 ]
i2 = i2 + 1;
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 13:
[preds: 10 12 ] [succs: 14 11 15 ]
if i2 < 20000 goto staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: java.lang.Class m2(java.lang.Object)>(r7);
"->"Block 14:
[preds: 13 ] [succs: 16 ]
goto [?= $r2 = <java.lang.System: java.io.PrintStream out>];
";
    "Block 13:
[preds: 10 12 ] [succs: 14 11 15 ]
if i2 < 20000 goto staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: java.lang.Class m2(java.lang.Object)>(r7);
"->"Block 11:
[preds: 13 ] [succs: 12 15 ]
staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: java.lang.Class m2(java.lang.Object)>(r7);
";
    "Block 13:
[preds: 10 12 ] [succs: 14 11 15 ]
if i2 < 20000 goto staticinvoke <compiler.profiling.TestMethodHandleInvokesIntrinsic: java.lang.Class m2(java.lang.Object)>(r7);
"->"Block 15:
[preds: 0 1 2 5 3 4 6 7 8 9 10 13 11 12 ] [succs: ]
$r3 := @caughtexception;
r8 = $r3;
$r4 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>(\"Unexpected exception\");
virtualinvoke r8.<java.lang.Throwable: void printStackTrace()>();
$r5 = new java.lang.RuntimeException;
specialinvoke $r5.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(\"TEST FAILED\", r8);
throw $r5;
";
    "Block 14:
[preds: 13 ] [succs: 16 ]
goto [?= $r2 = <java.lang.System: java.io.PrintStream out>];
"->"Block 16:
[preds: 14 ] [succs: ]
$r2 = <java.lang.System: java.io.PrintStream out>;
virtualinvoke $r2.<java.io.PrintStream: void println(java.lang.String)>(\"TEST PASSED\");
return;
";
}
