digraph "unitGraph" {
    "r4 := @parameter0: java.lang.String[]"
    "$r0 = new compiler.codegen.Test6431242"
    "specialinvoke $r0.<compiler.codegen.Test6431242: void <init>()>()"
    "r5 = $r0"
    "virtualinvoke r5.<compiler.codegen.Test6431242: void init()>()"
    "virtualinvoke r5.<compiler.codegen.Test6431242: void test()>()"
    "$r1 = <java.lang.System: java.io.PrintStream out>"
    "virtualinvoke $r1.<java.io.PrintStream: void println(java.lang.String)>(\"Passed\")"
    "goto [?= return]"
    "$r2 := @caughtexception"
    "r6 = $r2"
    "virtualinvoke r6.<java.lang.Exception: void printStackTrace()>()"
    "$r3 = <java.lang.System: java.io.PrintStream out>"
    "virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>(\"Failed\")"
    "return"
    "r4 := @parameter0: java.lang.String[]"->"$r0 = new compiler.codegen.Test6431242";
    "r4 := @parameter0: java.lang.String[]"->"$r2 := @caughtexception";
    "$r0 = new compiler.codegen.Test6431242"->"specialinvoke $r0.<compiler.codegen.Test6431242: void <init>()>()";
    "$r0 = new compiler.codegen.Test6431242"->"$r2 := @caughtexception";
    "specialinvoke $r0.<compiler.codegen.Test6431242: void <init>()>()"->"r5 = $r0";
    "specialinvoke $r0.<compiler.codegen.Test6431242: void <init>()>()"->"$r2 := @caughtexception";
    "r5 = $r0"->"virtualinvoke r5.<compiler.codegen.Test6431242: void init()>()";
    "r5 = $r0"->"$r2 := @caughtexception";
    "virtualinvoke r5.<compiler.codegen.Test6431242: void init()>()"->"virtualinvoke r5.<compiler.codegen.Test6431242: void test()>()";
    "virtualinvoke r5.<compiler.codegen.Test6431242: void init()>()"->"$r2 := @caughtexception";
    "virtualinvoke r5.<compiler.codegen.Test6431242: void test()>()"->"$r1 = <java.lang.System: java.io.PrintStream out>";
    "virtualinvoke r5.<compiler.codegen.Test6431242: void test()>()"->"$r2 := @caughtexception";
    "$r1 = <java.lang.System: java.io.PrintStream out>"->"virtualinvoke $r1.<java.io.PrintStream: void println(java.lang.String)>(\"Passed\")";
    "$r1 = <java.lang.System: java.io.PrintStream out>"->"$r2 := @caughtexception";
    "virtualinvoke $r1.<java.io.PrintStream: void println(java.lang.String)>(\"Passed\")"->"goto [?= return]";
    "virtualinvoke $r1.<java.io.PrintStream: void println(java.lang.String)>(\"Passed\")"->"$r2 := @caughtexception";
    "goto [?= return]"->"return";
    "$r2 := @caughtexception"->"r6 = $r2";
    "r6 = $r2"->"virtualinvoke r6.<java.lang.Exception: void printStackTrace()>()";
    "virtualinvoke r6.<java.lang.Exception: void printStackTrace()>()"->"$r3 = <java.lang.System: java.io.PrintStream out>";
    "$r3 = <java.lang.System: java.io.PrintStream out>"->"virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>(\"Failed\")";
    "virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>(\"Failed\")"->"return";
}
