digraph "unitGraph" {
    "r5 := @parameter0: java.lang.String[]"
    "$r0 = new jit.t.t014.t014"
    "specialinvoke $r0.<jit.t.t014.t014: void <init>()>()"
    "r6 = $r0"
    "virtualinvoke r6.<jit.t.t014.t014: void foo()>()"
    "goto [?= r7 = new java.lang.NullPointerException]"
    "$r3 := @caughtexception"
    "$r4 = new nsk.share.TestFailure"
    "specialinvoke $r4.<nsk.share.TestFailure: void <init>(java.lang.String)>(\"Exception thrown\")"
    "throw $r4"
    "r7 = new java.lang.NullPointerException"
    "specialinvoke r7.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke o#2.<jit.t.t014.t014: void foo()>()\")"
    "throw r7"
    "$r2 := @caughtexception"
    "return"
    "r5 := @parameter0: java.lang.String[]"->"$r0 = new jit.t.t014.t014";
    "$r0 = new jit.t.t014.t014"->"specialinvoke $r0.<jit.t.t014.t014: void <init>()>()";
    "specialinvoke $r0.<jit.t.t014.t014: void <init>()>()"->"r6 = $r0";
    "r6 = $r0"->"virtualinvoke r6.<jit.t.t014.t014: void foo()>()";
    "r6 = $r0"->"$r3 := @caughtexception";
    "virtualinvoke r6.<jit.t.t014.t014: void foo()>()"->"goto [?= r7 = new java.lang.NullPointerException]";
    "virtualinvoke r6.<jit.t.t014.t014: void foo()>()"->"$r3 := @caughtexception";
    "goto [?= r7 = new java.lang.NullPointerException]"->"r7 = new java.lang.NullPointerException";
    "goto [?= r7 = new java.lang.NullPointerException]"->"$r2 := @caughtexception";
    "$r3 := @caughtexception"->"$r4 = new nsk.share.TestFailure";
    "$r4 = new nsk.share.TestFailure"->"specialinvoke $r4.<nsk.share.TestFailure: void <init>(java.lang.String)>(\"Exception thrown\")";
    "specialinvoke $r4.<nsk.share.TestFailure: void <init>(java.lang.String)>(\"Exception thrown\")"->"throw $r4";
    "r7 = new java.lang.NullPointerException"->"specialinvoke r7.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke o#2.<jit.t.t014.t014: void foo()>()\")";
    "r7 = new java.lang.NullPointerException"->"$r2 := @caughtexception";
    "specialinvoke r7.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke o#2.<jit.t.t014.t014: void foo()>()\")"->"throw r7";
    "specialinvoke r7.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke o#2.<jit.t.t014.t014: void foo()>()\")"->"$r2 := @caughtexception";
    "throw r7"->"$r2 := @caughtexception";
    "$r2 := @caughtexception"->"return";
}
