digraph "unitGraph" {
    "r1 := @parameter0: java.lang.String"
    "r2 := @parameter1: java.lang.String"
    "r3 := @parameter2: java.lang.String"
    "$r0 = new java.nio.file.FileSystemException"
    "specialinvoke $r0.<java.nio.file.FileSystemException: void <init>(java.lang.String,java.lang.String,java.lang.String)>(r1, r2, r3)"
    "r4 = $r0"
    "$r5 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getFile()>()"
    "$z0 = staticinvoke <java.util.Objects: boolean equals(java.lang.Object,java.lang.Object)>(r1, $r5)"
    "if $z0 != 0 goto $r6 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getOtherFile()>()"
    "$r10 = new java.lang.RuntimeException"
    "specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"getFile returned unexpected result\")"
    "throw $r10"
    "$r6 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getOtherFile()>()"
    "$z1 = staticinvoke <java.util.Objects: boolean equals(java.lang.Object,java.lang.Object)>(r2, $r6)"
    "if $z1 != 0 goto $r7 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getReason()>()"
    "$r9 = new java.lang.RuntimeException"
    "specialinvoke $r9.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"getOtherFile returned unexpected result\")"
    "throw $r9"
    "$r7 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getReason()>()"
    "$z2 = staticinvoke <java.util.Objects: boolean equals(java.lang.Object,java.lang.Object)>(r3, $r7)"
    "if $z2 != 0 goto return"
    "$r8 = new java.lang.RuntimeException"
    "specialinvoke $r8.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"getReason returned unexpected result\")"
    "throw $r8"
    "return"
    "r1 := @parameter0: java.lang.String"->"r2 := @parameter1: java.lang.String";
    "r2 := @parameter1: java.lang.String"->"r3 := @parameter2: java.lang.String";
    "r3 := @parameter2: java.lang.String"->"$r0 = new java.nio.file.FileSystemException";
    "$r0 = new java.nio.file.FileSystemException"->"specialinvoke $r0.<java.nio.file.FileSystemException: void <init>(java.lang.String,java.lang.String,java.lang.String)>(r1, r2, r3)";
    "specialinvoke $r0.<java.nio.file.FileSystemException: void <init>(java.lang.String,java.lang.String,java.lang.String)>(r1, r2, r3)"->"r4 = $r0";
    "r4 = $r0"->"$r5 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getFile()>()";
    "$r5 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getFile()>()"->"$z0 = staticinvoke <java.util.Objects: boolean equals(java.lang.Object,java.lang.Object)>(r1, $r5)";
    "$z0 = staticinvoke <java.util.Objects: boolean equals(java.lang.Object,java.lang.Object)>(r1, $r5)"->"if $z0 != 0 goto $r6 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getOtherFile()>()";
    "if $z0 != 0 goto $r6 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getOtherFile()>()"->"$r10 = new java.lang.RuntimeException";
    "if $z0 != 0 goto $r6 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getOtherFile()>()"->"$r6 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getOtherFile()>()";
    "$r10 = new java.lang.RuntimeException"->"specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"getFile returned unexpected result\")";
    "specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"getFile returned unexpected result\")"->"throw $r10";
    "$r6 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getOtherFile()>()"->"$z1 = staticinvoke <java.util.Objects: boolean equals(java.lang.Object,java.lang.Object)>(r2, $r6)";
    "$z1 = staticinvoke <java.util.Objects: boolean equals(java.lang.Object,java.lang.Object)>(r2, $r6)"->"if $z1 != 0 goto $r7 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getReason()>()";
    "if $z1 != 0 goto $r7 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getReason()>()"->"$r9 = new java.lang.RuntimeException";
    "if $z1 != 0 goto $r7 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getReason()>()"->"$r7 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getReason()>()";
    "$r9 = new java.lang.RuntimeException"->"specialinvoke $r9.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"getOtherFile returned unexpected result\")";
    "specialinvoke $r9.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"getOtherFile returned unexpected result\")"->"throw $r9";
    "$r7 = virtualinvoke r4.<java.nio.file.FileSystemException: java.lang.String getReason()>()"->"$z2 = staticinvoke <java.util.Objects: boolean equals(java.lang.Object,java.lang.Object)>(r3, $r7)";
    "$z2 = staticinvoke <java.util.Objects: boolean equals(java.lang.Object,java.lang.Object)>(r3, $r7)"->"if $z2 != 0 goto return";
    "if $z2 != 0 goto return"->"$r8 = new java.lang.RuntimeException";
    "if $z2 != 0 goto return"->"return";
    "$r8 = new java.lang.RuntimeException"->"specialinvoke $r8.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"getReason returned unexpected result\")";
    "specialinvoke $r8.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"getReason returned unexpected result\")"->"throw $r8";
}
