digraph "unitGraph" {
    "r31 := @parameter0: java.lang.String[]"
    "$r0 = newarray (java.math.BigInteger)[3]"
    "$r1 = <java.math.BigInteger: java.math.BigInteger ZERO>"
    "$r0[0] = $r1"
    "$r2 = <java.math.BigInteger: java.math.BigInteger ONE>"
    "$r0[1] = $r2"
    "$r3 = <java.math.BigInteger: java.math.BigInteger TEN>"
    "$r0[2] = $r3"
    "r4 = $r0"
    "r5 = r4"
    "i0 = lengthof r5"
    "i1 = 0"
    "if i1 >= i0 goto return"
    "r6 = r5[i1]"
    "r32 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger multiply(java.math.BigInteger)>(null)"
    "$r7 = new java.lang.RuntimeException"
    "$r8 = new java.lang.StringBuilder"
    "specialinvoke $r8.<java.lang.StringBuilder: void <init>()>()"
    "$r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")"
    "$r10 = virtualinvoke $r9.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r32)"
    "$r11 = virtualinvoke $r10.<java.lang.StringBuilder: java.lang.String toString()>()"
    "specialinvoke $r7.<java.lang.RuntimeException: void <init>(java.lang.String)>($r11)"
    "throw $r7"
    "$r25 := @caughtexception"
    "r33 = $r25"
    "r34 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger divide(java.math.BigInteger)>(null)"
    "$r26 = new java.lang.RuntimeException"
    "$r27 = new java.lang.StringBuilder"
    "specialinvoke $r27.<java.lang.StringBuilder: void <init>()>()"
    "$r28 = virtualinvoke $r27.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")"
    "$r29 = virtualinvoke $r28.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r34)"
    "$r30 = virtualinvoke $r29.<java.lang.StringBuilder: java.lang.String toString()>()"
    "specialinvoke $r26.<java.lang.RuntimeException: void <init>(java.lang.String)>($r30)"
    "throw $r26"
    "$r19 := @caughtexception"
    "r35 = $r19"
    "r36 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger add(java.math.BigInteger)>(null)"
    "$r20 = new java.lang.RuntimeException"
    "$r21 = new java.lang.StringBuilder"
    "specialinvoke $r21.<java.lang.StringBuilder: void <init>()>()"
    "$r22 = virtualinvoke $r21.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")"
    "$r23 = virtualinvoke $r22.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r36)"
    "$r24 = virtualinvoke $r23.<java.lang.StringBuilder: java.lang.String toString()>()"
    "specialinvoke $r20.<java.lang.RuntimeException: void <init>(java.lang.String)>($r24)"
    "throw $r20"
    "$r13 := @caughtexception"
    "r37 = $r13"
    "r38 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger subtract(java.math.BigInteger)>(null)"
    "$r14 = new java.lang.RuntimeException"
    "$r15 = new java.lang.StringBuilder"
    "specialinvoke $r15.<java.lang.StringBuilder: void <init>()>()"
    "$r16 = virtualinvoke $r15.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")"
    "$r17 = virtualinvoke $r16.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r38)"
    "$r18 = virtualinvoke $r17.<java.lang.StringBuilder: java.lang.String toString()>()"
    "specialinvoke $r14.<java.lang.RuntimeException: void <init>(java.lang.String)>($r18)"
    "throw $r14"
    "$r12 := @caughtexception"
    "r39 = $r12"
    "i1 = i1 + 1"
    "goto [?= (branch)]"
    "return"
    "r31 := @parameter0: java.lang.String[]"->"$r0 = newarray (java.math.BigInteger)[3]";
    "$r0 = newarray (java.math.BigInteger)[3]"->"$r1 = <java.math.BigInteger: java.math.BigInteger ZERO>";
    "$r1 = <java.math.BigInteger: java.math.BigInteger ZERO>"->"$r0[0] = $r1";
    "$r0[0] = $r1"->"$r2 = <java.math.BigInteger: java.math.BigInteger ONE>";
    "$r2 = <java.math.BigInteger: java.math.BigInteger ONE>"->"$r0[1] = $r2";
    "$r0[1] = $r2"->"$r3 = <java.math.BigInteger: java.math.BigInteger TEN>";
    "$r3 = <java.math.BigInteger: java.math.BigInteger TEN>"->"$r0[2] = $r3";
    "$r0[2] = $r3"->"r4 = $r0";
    "r4 = $r0"->"r5 = r4";
    "r5 = r4"->"i0 = lengthof r5";
    "i0 = lengthof r5"->"i1 = 0";
    "i1 = 0"->"if i1 >= i0 goto return";
    "if i1 >= i0 goto return"->"r6 = r5[i1]";
    "if i1 >= i0 goto return"->"return";
    "r6 = r5[i1]"->"r32 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger multiply(java.math.BigInteger)>(null)";
    "r6 = r5[i1]"->"$r25 := @caughtexception";
    "r32 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger multiply(java.math.BigInteger)>(null)"->"$r7 = new java.lang.RuntimeException";
    "r32 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger multiply(java.math.BigInteger)>(null)"->"$r25 := @caughtexception";
    "$r7 = new java.lang.RuntimeException"->"$r8 = new java.lang.StringBuilder";
    "$r7 = new java.lang.RuntimeException"->"$r25 := @caughtexception";
    "$r8 = new java.lang.StringBuilder"->"specialinvoke $r8.<java.lang.StringBuilder: void <init>()>()";
    "$r8 = new java.lang.StringBuilder"->"$r25 := @caughtexception";
    "specialinvoke $r8.<java.lang.StringBuilder: void <init>()>()"->"$r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")";
    "specialinvoke $r8.<java.lang.StringBuilder: void <init>()>()"->"$r25 := @caughtexception";
    "$r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")"->"$r10 = virtualinvoke $r9.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r32)";
    "$r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")"->"$r25 := @caughtexception";
    "$r10 = virtualinvoke $r9.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r32)"->"$r11 = virtualinvoke $r10.<java.lang.StringBuilder: java.lang.String toString()>()";
    "$r10 = virtualinvoke $r9.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r32)"->"$r25 := @caughtexception";
    "$r11 = virtualinvoke $r10.<java.lang.StringBuilder: java.lang.String toString()>()"->"specialinvoke $r7.<java.lang.RuntimeException: void <init>(java.lang.String)>($r11)";
    "$r11 = virtualinvoke $r10.<java.lang.StringBuilder: java.lang.String toString()>()"->"$r25 := @caughtexception";
    "specialinvoke $r7.<java.lang.RuntimeException: void <init>(java.lang.String)>($r11)"->"throw $r7";
    "specialinvoke $r7.<java.lang.RuntimeException: void <init>(java.lang.String)>($r11)"->"$r25 := @caughtexception";
    "throw $r7"->"$r25 := @caughtexception";
    "$r25 := @caughtexception"->"r33 = $r25";
    "r33 = $r25"->"r34 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger divide(java.math.BigInteger)>(null)";
    "r33 = $r25"->"$r19 := @caughtexception";
    "r34 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger divide(java.math.BigInteger)>(null)"->"$r26 = new java.lang.RuntimeException";
    "r34 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger divide(java.math.BigInteger)>(null)"->"$r19 := @caughtexception";
    "$r26 = new java.lang.RuntimeException"->"$r27 = new java.lang.StringBuilder";
    "$r26 = new java.lang.RuntimeException"->"$r19 := @caughtexception";
    "$r27 = new java.lang.StringBuilder"->"specialinvoke $r27.<java.lang.StringBuilder: void <init>()>()";
    "$r27 = new java.lang.StringBuilder"->"$r19 := @caughtexception";
    "specialinvoke $r27.<java.lang.StringBuilder: void <init>()>()"->"$r28 = virtualinvoke $r27.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")";
    "specialinvoke $r27.<java.lang.StringBuilder: void <init>()>()"->"$r19 := @caughtexception";
    "$r28 = virtualinvoke $r27.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")"->"$r29 = virtualinvoke $r28.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r34)";
    "$r28 = virtualinvoke $r27.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")"->"$r19 := @caughtexception";
    "$r29 = virtualinvoke $r28.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r34)"->"$r30 = virtualinvoke $r29.<java.lang.StringBuilder: java.lang.String toString()>()";
    "$r29 = virtualinvoke $r28.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r34)"->"$r19 := @caughtexception";
    "$r30 = virtualinvoke $r29.<java.lang.StringBuilder: java.lang.String toString()>()"->"specialinvoke $r26.<java.lang.RuntimeException: void <init>(java.lang.String)>($r30)";
    "$r30 = virtualinvoke $r29.<java.lang.StringBuilder: java.lang.String toString()>()"->"$r19 := @caughtexception";
    "specialinvoke $r26.<java.lang.RuntimeException: void <init>(java.lang.String)>($r30)"->"throw $r26";
    "specialinvoke $r26.<java.lang.RuntimeException: void <init>(java.lang.String)>($r30)"->"$r19 := @caughtexception";
    "throw $r26"->"$r19 := @caughtexception";
    "$r19 := @caughtexception"->"r35 = $r19";
    "r35 = $r19"->"r36 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger add(java.math.BigInteger)>(null)";
    "r35 = $r19"->"$r13 := @caughtexception";
    "r36 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger add(java.math.BigInteger)>(null)"->"$r20 = new java.lang.RuntimeException";
    "r36 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger add(java.math.BigInteger)>(null)"->"$r13 := @caughtexception";
    "$r20 = new java.lang.RuntimeException"->"$r21 = new java.lang.StringBuilder";
    "$r20 = new java.lang.RuntimeException"->"$r13 := @caughtexception";
    "$r21 = new java.lang.StringBuilder"->"specialinvoke $r21.<java.lang.StringBuilder: void <init>()>()";
    "$r21 = new java.lang.StringBuilder"->"$r13 := @caughtexception";
    "specialinvoke $r21.<java.lang.StringBuilder: void <init>()>()"->"$r22 = virtualinvoke $r21.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")";
    "specialinvoke $r21.<java.lang.StringBuilder: void <init>()>()"->"$r13 := @caughtexception";
    "$r22 = virtualinvoke $r21.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")"->"$r23 = virtualinvoke $r22.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r36)";
    "$r22 = virtualinvoke $r21.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")"->"$r13 := @caughtexception";
    "$r23 = virtualinvoke $r22.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r36)"->"$r24 = virtualinvoke $r23.<java.lang.StringBuilder: java.lang.String toString()>()";
    "$r23 = virtualinvoke $r22.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r36)"->"$r13 := @caughtexception";
    "$r24 = virtualinvoke $r23.<java.lang.StringBuilder: java.lang.String toString()>()"->"specialinvoke $r20.<java.lang.RuntimeException: void <init>(java.lang.String)>($r24)";
    "$r24 = virtualinvoke $r23.<java.lang.StringBuilder: java.lang.String toString()>()"->"$r13 := @caughtexception";
    "specialinvoke $r20.<java.lang.RuntimeException: void <init>(java.lang.String)>($r24)"->"throw $r20";
    "specialinvoke $r20.<java.lang.RuntimeException: void <init>(java.lang.String)>($r24)"->"$r13 := @caughtexception";
    "throw $r20"->"$r13 := @caughtexception";
    "$r13 := @caughtexception"->"r37 = $r13";
    "r37 = $r13"->"r38 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger subtract(java.math.BigInteger)>(null)";
    "r37 = $r13"->"$r12 := @caughtexception";
    "r38 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger subtract(java.math.BigInteger)>(null)"->"$r14 = new java.lang.RuntimeException";
    "r38 = virtualinvoke r6.<java.math.BigInteger: java.math.BigInteger subtract(java.math.BigInteger)>(null)"->"$r12 := @caughtexception";
    "$r14 = new java.lang.RuntimeException"->"$r15 = new java.lang.StringBuilder";
    "$r14 = new java.lang.RuntimeException"->"$r12 := @caughtexception";
    "$r15 = new java.lang.StringBuilder"->"specialinvoke $r15.<java.lang.StringBuilder: void <init>()>()";
    "$r15 = new java.lang.StringBuilder"->"$r12 := @caughtexception";
    "specialinvoke $r15.<java.lang.StringBuilder: void <init>()>()"->"$r16 = virtualinvoke $r15.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")";
    "specialinvoke $r15.<java.lang.StringBuilder: void <init>()>()"->"$r12 := @caughtexception";
    "$r16 = virtualinvoke $r15.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")"->"$r17 = virtualinvoke $r16.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r38)";
    "$r16 = virtualinvoke $r15.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(\"Instead of NPE got \")"->"$r12 := @caughtexception";
    "$r17 = virtualinvoke $r16.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r38)"->"$r18 = virtualinvoke $r17.<java.lang.StringBuilder: java.lang.String toString()>()";
    "$r17 = virtualinvoke $r16.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>(r38)"->"$r12 := @caughtexception";
    "$r18 = virtualinvoke $r17.<java.lang.StringBuilder: java.lang.String toString()>()"->"specialinvoke $r14.<java.lang.RuntimeException: void <init>(java.lang.String)>($r18)";
    "$r18 = virtualinvoke $r17.<java.lang.StringBuilder: java.lang.String toString()>()"->"$r12 := @caughtexception";
    "specialinvoke $r14.<java.lang.RuntimeException: void <init>(java.lang.String)>($r18)"->"throw $r14";
    "specialinvoke $r14.<java.lang.RuntimeException: void <init>(java.lang.String)>($r18)"->"$r12 := @caughtexception";
    "throw $r14"->"$r12 := @caughtexception";
    "$r12 := @caughtexception"->"r39 = $r12";
    "r39 = $r12"->"i1 = i1 + 1";
    "i1 = i1 + 1"->"goto [?= (branch)]";
    "goto [?= (branch)]"->"if i1 >= i0 goto return";
}
