digraph "unitGraph" {
    "r16 := @parameter0: java.lang.String[]"
    "r0 = newarray (byte)[0]"
    "b0 = 4"
    "i1 = 2147483644"
    "$r1 = new java.util.zip.CRC32"
    "specialinvoke $r1.<java.util.zip.CRC32: void <init>()>()"
    "virtualinvoke $r1.<java.util.zip.CRC32: void update(byte[],int,int)>(r0, b0, i1)"
    "$r2 = new java.lang.RuntimeException"
    "specialinvoke $r2.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"
    "throw $r2"
    "$r13 := @caughtexception"
    "r17 = $r13"
    "$r14 = new java.util.zip.Deflater"
    "specialinvoke $r14.<java.util.zip.Deflater: void <init>()>()"
    "virtualinvoke $r14.<java.util.zip.Deflater: void setDictionary(byte[],int,int)>(r0, b0, i1)"
    "$r15 = new java.lang.RuntimeException"
    "specialinvoke $r15.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"
    "throw $r15"
    "$r10 := @caughtexception"
    "r18 = $r10"
    "$r11 = new java.util.zip.Adler32"
    "specialinvoke $r11.<java.util.zip.Adler32: void <init>()>()"
    "virtualinvoke $r11.<java.util.zip.Adler32: void update(byte[],int,int)>(r0, b0, i1)"
    "$r12 = new java.lang.RuntimeException"
    "specialinvoke $r12.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"
    "throw $r12"
    "$r7 := @caughtexception"
    "r19 = $r7"
    "$r8 = new java.util.zip.Deflater"
    "specialinvoke $r8.<java.util.zip.Deflater: void <init>()>()"
    "virtualinvoke $r8.<java.util.zip.Deflater: int deflate(byte[],int,int)>(r0, b0, i1)"
    "$r9 = new java.lang.RuntimeException"
    "specialinvoke $r9.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"
    "throw $r9"
    "$r4 := @caughtexception"
    "r20 = $r4"
    "$r5 = new java.util.zip.Inflater"
    "specialinvoke $r5.<java.util.zip.Inflater: void <init>()>()"
    "virtualinvoke $r5.<java.util.zip.Inflater: int inflate(byte[],int,int)>(r0, b0, i1)"
    "$r6 = new java.lang.RuntimeException"
    "specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"
    "throw $r6"
    "$r3 := @caughtexception"
    "r21 = $r3"
    "return"
    "r16 := @parameter0: java.lang.String[]"->"r0 = newarray (byte)[0]";
    "r0 = newarray (byte)[0]"->"b0 = 4";
    "b0 = 4"->"i1 = 2147483644";
    "i1 = 2147483644"->"$r1 = new java.util.zip.CRC32";
    "i1 = 2147483644"->"$r13 := @caughtexception";
    "$r1 = new java.util.zip.CRC32"->"specialinvoke $r1.<java.util.zip.CRC32: void <init>()>()";
    "$r1 = new java.util.zip.CRC32"->"$r13 := @caughtexception";
    "specialinvoke $r1.<java.util.zip.CRC32: void <init>()>()"->"virtualinvoke $r1.<java.util.zip.CRC32: void update(byte[],int,int)>(r0, b0, i1)";
    "specialinvoke $r1.<java.util.zip.CRC32: void <init>()>()"->"$r13 := @caughtexception";
    "virtualinvoke $r1.<java.util.zip.CRC32: void update(byte[],int,int)>(r0, b0, i1)"->"$r2 = new java.lang.RuntimeException";
    "virtualinvoke $r1.<java.util.zip.CRC32: void update(byte[],int,int)>(r0, b0, i1)"->"$r13 := @caughtexception";
    "$r2 = new java.lang.RuntimeException"->"specialinvoke $r2.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")";
    "$r2 = new java.lang.RuntimeException"->"$r13 := @caughtexception";
    "specialinvoke $r2.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"throw $r2";
    "specialinvoke $r2.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"$r13 := @caughtexception";
    "throw $r2"->"$r13 := @caughtexception";
    "$r13 := @caughtexception"->"r17 = $r13";
    "r17 = $r13"->"$r14 = new java.util.zip.Deflater";
    "r17 = $r13"->"$r10 := @caughtexception";
    "$r14 = new java.util.zip.Deflater"->"specialinvoke $r14.<java.util.zip.Deflater: void <init>()>()";
    "$r14 = new java.util.zip.Deflater"->"$r10 := @caughtexception";
    "specialinvoke $r14.<java.util.zip.Deflater: void <init>()>()"->"virtualinvoke $r14.<java.util.zip.Deflater: void setDictionary(byte[],int,int)>(r0, b0, i1)";
    "specialinvoke $r14.<java.util.zip.Deflater: void <init>()>()"->"$r10 := @caughtexception";
    "virtualinvoke $r14.<java.util.zip.Deflater: void setDictionary(byte[],int,int)>(r0, b0, i1)"->"$r15 = new java.lang.RuntimeException";
    "virtualinvoke $r14.<java.util.zip.Deflater: void setDictionary(byte[],int,int)>(r0, b0, i1)"->"$r10 := @caughtexception";
    "$r15 = new java.lang.RuntimeException"->"specialinvoke $r15.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")";
    "$r15 = new java.lang.RuntimeException"->"$r10 := @caughtexception";
    "specialinvoke $r15.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"throw $r15";
    "specialinvoke $r15.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"$r10 := @caughtexception";
    "throw $r15"->"$r10 := @caughtexception";
    "$r10 := @caughtexception"->"r18 = $r10";
    "r18 = $r10"->"$r11 = new java.util.zip.Adler32";
    "r18 = $r10"->"$r7 := @caughtexception";
    "$r11 = new java.util.zip.Adler32"->"specialinvoke $r11.<java.util.zip.Adler32: void <init>()>()";
    "$r11 = new java.util.zip.Adler32"->"$r7 := @caughtexception";
    "specialinvoke $r11.<java.util.zip.Adler32: void <init>()>()"->"virtualinvoke $r11.<java.util.zip.Adler32: void update(byte[],int,int)>(r0, b0, i1)";
    "specialinvoke $r11.<java.util.zip.Adler32: void <init>()>()"->"$r7 := @caughtexception";
    "virtualinvoke $r11.<java.util.zip.Adler32: void update(byte[],int,int)>(r0, b0, i1)"->"$r12 = new java.lang.RuntimeException";
    "virtualinvoke $r11.<java.util.zip.Adler32: void update(byte[],int,int)>(r0, b0, i1)"->"$r7 := @caughtexception";
    "$r12 = new java.lang.RuntimeException"->"specialinvoke $r12.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")";
    "$r12 = new java.lang.RuntimeException"->"$r7 := @caughtexception";
    "specialinvoke $r12.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"throw $r12";
    "specialinvoke $r12.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"$r7 := @caughtexception";
    "throw $r12"->"$r7 := @caughtexception";
    "$r7 := @caughtexception"->"r19 = $r7";
    "r19 = $r7"->"$r8 = new java.util.zip.Deflater";
    "r19 = $r7"->"$r4 := @caughtexception";
    "$r8 = new java.util.zip.Deflater"->"specialinvoke $r8.<java.util.zip.Deflater: void <init>()>()";
    "$r8 = new java.util.zip.Deflater"->"$r4 := @caughtexception";
    "specialinvoke $r8.<java.util.zip.Deflater: void <init>()>()"->"virtualinvoke $r8.<java.util.zip.Deflater: int deflate(byte[],int,int)>(r0, b0, i1)";
    "specialinvoke $r8.<java.util.zip.Deflater: void <init>()>()"->"$r4 := @caughtexception";
    "virtualinvoke $r8.<java.util.zip.Deflater: int deflate(byte[],int,int)>(r0, b0, i1)"->"$r9 = new java.lang.RuntimeException";
    "virtualinvoke $r8.<java.util.zip.Deflater: int deflate(byte[],int,int)>(r0, b0, i1)"->"$r4 := @caughtexception";
    "$r9 = new java.lang.RuntimeException"->"specialinvoke $r9.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")";
    "$r9 = new java.lang.RuntimeException"->"$r4 := @caughtexception";
    "specialinvoke $r9.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"throw $r9";
    "specialinvoke $r9.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"$r4 := @caughtexception";
    "throw $r9"->"$r4 := @caughtexception";
    "$r4 := @caughtexception"->"r20 = $r4";
    "r20 = $r4"->"$r5 = new java.util.zip.Inflater";
    "r20 = $r4"->"$r3 := @caughtexception";
    "$r5 = new java.util.zip.Inflater"->"specialinvoke $r5.<java.util.zip.Inflater: void <init>()>()";
    "$r5 = new java.util.zip.Inflater"->"$r3 := @caughtexception";
    "specialinvoke $r5.<java.util.zip.Inflater: void <init>()>()"->"virtualinvoke $r5.<java.util.zip.Inflater: int inflate(byte[],int,int)>(r0, b0, i1)";
    "specialinvoke $r5.<java.util.zip.Inflater: void <init>()>()"->"$r3 := @caughtexception";
    "virtualinvoke $r5.<java.util.zip.Inflater: int inflate(byte[],int,int)>(r0, b0, i1)"->"$r6 = new java.lang.RuntimeException";
    "virtualinvoke $r5.<java.util.zip.Inflater: int inflate(byte[],int,int)>(r0, b0, i1)"->"$r3 := @caughtexception";
    "$r6 = new java.lang.RuntimeException"->"specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")";
    "$r6 = new java.lang.RuntimeException"->"$r3 := @caughtexception";
    "specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"throw $r6";
    "specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Expected exception not thrown\")"->"$r3 := @caughtexception";
    "throw $r6"->"$r3 := @caughtexception";
    "$r3 := @caughtexception"->"r21 = $r3";
    "r21 = $r3"->"return";
}
