digraph "unitGraph" {
    "r0 := @parameter0: java.lang.Class"
    "r2 := @parameter1: java.lang.Enum"
    "r1 = staticinvoke <java.util.EnumSet: java.util.EnumSet noneOf(java.lang.Class)>(r0)"
    "$r3 = staticinvoke <java.util.Collections: java.util.Set singleton(java.lang.Object)>(r2)"
    "virtualinvoke r1.<java.util.EnumSet: boolean addAll(java.util.Collection)>($r3)"
    "goto [?= $r4 = new java.lang.RuntimeException]"
    "$r5 := @caughtexception"
    "r6 = $r5"
    "return"
    "$r4 = new java.lang.RuntimeException"
    "specialinvoke $r4.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Incorrectly typed addAll succeeded\")"
    "throw $r4"
    "r0 := @parameter0: java.lang.Class"->"r2 := @parameter1: java.lang.Enum";
    "r2 := @parameter1: java.lang.Enum"->"r1 = staticinvoke <java.util.EnumSet: java.util.EnumSet noneOf(java.lang.Class)>(r0)";
    "r1 = staticinvoke <java.util.EnumSet: java.util.EnumSet noneOf(java.lang.Class)>(r0)"->"$r3 = staticinvoke <java.util.Collections: java.util.Set singleton(java.lang.Object)>(r2)";
    "r1 = staticinvoke <java.util.EnumSet: java.util.EnumSet noneOf(java.lang.Class)>(r0)"->"$r5 := @caughtexception";
    "$r3 = staticinvoke <java.util.Collections: java.util.Set singleton(java.lang.Object)>(r2)"->"virtualinvoke r1.<java.util.EnumSet: boolean addAll(java.util.Collection)>($r3)";
    "$r3 = staticinvoke <java.util.Collections: java.util.Set singleton(java.lang.Object)>(r2)"->"$r5 := @caughtexception";
    "virtualinvoke r1.<java.util.EnumSet: boolean addAll(java.util.Collection)>($r3)"->"goto [?= $r4 = new java.lang.RuntimeException]";
    "virtualinvoke r1.<java.util.EnumSet: boolean addAll(java.util.Collection)>($r3)"->"$r5 := @caughtexception";
    "goto [?= $r4 = new java.lang.RuntimeException]"->"$r4 = new java.lang.RuntimeException";
    "$r5 := @caughtexception"->"r6 = $r5";
    "r6 = $r5"->"return";
    "$r4 = new java.lang.RuntimeException"->"specialinvoke $r4.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Incorrectly typed addAll succeeded\")";
    "specialinvoke $r4.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Incorrectly typed addAll succeeded\")"->"throw $r4";
}
