digraph "unitGraph" {
    "Block 0:
[preds: ] [succs: 1 5 ]
r11 := @parameter0: java.lang.String[];
"
    "Block 1:
[preds: 0 ] [succs: 2 5 ]
$r1 = class \"LjavaT/lang/reflect/Method/invoke/ErrorInInvoke;\";
"
    "Block 2:
[preds: 1 ] [succs: 3 5 ]
$r0 = newarray (java.lang.Class)[0];
"
    "Block 3:
[preds: 2 ] [succs: 4 5 ]
r12 = virtualinvoke $r1.<java.lang.Class: java.lang.reflect.Method getMethod(java.lang.String,java.lang.Class[])>(\"run\", $r0);
"
    "Block 4:
[preds: 3 ] [succs: 8 9 12 6 ]
goto [?= virtualinvoke r12.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, null)];
"
    "Block 5:
[preds: 0 1 2 3 ] [succs: ]
$r9 := @caughtexception;
$r10 = new java.lang.RuntimeException;
specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Test failed (getMethod() failed\");
throw $r10;
"
    "Block 6:
[preds: 4 ] [succs: 8 9 12 7 ]
virtualinvoke r12.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, null);
"
    "Block 7:
[preds: 6 ] [succs: 13 ]
goto [?= return];
"
    "Block 8:
[preds: 4 6 ] [succs: ]
$r7 := @caughtexception;
$r8 = new java.lang.RuntimeException;
specialinvoke $r8.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Test failed (AbstractMethodError passed through)\");
throw $r8;
"
    "Block 9:
[preds: 4 6 ] [succs: 10 11 ]
$r4 := @caughtexception;
r13 = $r4;
r5 = virtualinvoke r13.<java.lang.reflect.InvocationTargetException: java.lang.Throwable getTargetException()>();
$z0 = r5 instanceof java.lang.AbstractMethodError;
if $z0 != 0 goto (branch);
"
    "Block 10:
[preds: 9 ] [succs: ]
$r6 = new java.lang.RuntimeException;
specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Test failed (InvocationTargetException didn\'t wrap AbstractMethodError)\");
throw $r6;
"
    "Block 11:
[preds: 9 ] [succs: 13 ]
goto [?= return];
"
    "Block 12:
[preds: 4 6 ] [succs: ]
$r2 := @caughtexception;
$r3 = new java.lang.RuntimeException;
specialinvoke $r3.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Test failed (Unexpected exception)\");
throw $r3;
"
    "Block 13:
[preds: 7 11 ] [succs: ]
return;
"
    "Block 0:
[preds: ] [succs: 1 5 ]
r11 := @parameter0: java.lang.String[];
"->"Block 1:
[preds: 0 ] [succs: 2 5 ]
$r1 = class \"LjavaT/lang/reflect/Method/invoke/ErrorInInvoke;\";
";
    "Block 0:
[preds: ] [succs: 1 5 ]
r11 := @parameter0: java.lang.String[];
"->"Block 5:
[preds: 0 1 2 3 ] [succs: ]
$r9 := @caughtexception;
$r10 = new java.lang.RuntimeException;
specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Test failed (getMethod() failed\");
throw $r10;
";
    "Block 1:
[preds: 0 ] [succs: 2 5 ]
$r1 = class \"LjavaT/lang/reflect/Method/invoke/ErrorInInvoke;\";
"->"Block 2:
[preds: 1 ] [succs: 3 5 ]
$r0 = newarray (java.lang.Class)[0];
";
    "Block 1:
[preds: 0 ] [succs: 2 5 ]
$r1 = class \"LjavaT/lang/reflect/Method/invoke/ErrorInInvoke;\";
"->"Block 5:
[preds: 0 1 2 3 ] [succs: ]
$r9 := @caughtexception;
$r10 = new java.lang.RuntimeException;
specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Test failed (getMethod() failed\");
throw $r10;
";
    "Block 2:
[preds: 1 ] [succs: 3 5 ]
$r0 = newarray (java.lang.Class)[0];
"->"Block 3:
[preds: 2 ] [succs: 4 5 ]
r12 = virtualinvoke $r1.<java.lang.Class: java.lang.reflect.Method getMethod(java.lang.String,java.lang.Class[])>(\"run\", $r0);
";
    "Block 2:
[preds: 1 ] [succs: 3 5 ]
$r0 = newarray (java.lang.Class)[0];
"->"Block 5:
[preds: 0 1 2 3 ] [succs: ]
$r9 := @caughtexception;
$r10 = new java.lang.RuntimeException;
specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Test failed (getMethod() failed\");
throw $r10;
";
    "Block 3:
[preds: 2 ] [succs: 4 5 ]
r12 = virtualinvoke $r1.<java.lang.Class: java.lang.reflect.Method getMethod(java.lang.String,java.lang.Class[])>(\"run\", $r0);
"->"Block 4:
[preds: 3 ] [succs: 8 9 12 6 ]
goto [?= virtualinvoke r12.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, null)];
";
    "Block 3:
[preds: 2 ] [succs: 4 5 ]
r12 = virtualinvoke $r1.<java.lang.Class: java.lang.reflect.Method getMethod(java.lang.String,java.lang.Class[])>(\"run\", $r0);
"->"Block 5:
[preds: 0 1 2 3 ] [succs: ]
$r9 := @caughtexception;
$r10 = new java.lang.RuntimeException;
specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Test failed (getMethod() failed\");
throw $r10;
";
    "Block 4:
[preds: 3 ] [succs: 8 9 12 6 ]
goto [?= virtualinvoke r12.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, null)];
"->"Block 8:
[preds: 4 6 ] [succs: ]
$r7 := @caughtexception;
$r8 = new java.lang.RuntimeException;
specialinvoke $r8.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Test failed (AbstractMethodError passed through)\");
throw $r8;
";
    "Block 4:
[preds: 3 ] [succs: 8 9 12 6 ]
goto [?= virtualinvoke r12.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, null)];
"->"Block 9:
[preds: 4 6 ] [succs: 10 11 ]
$r4 := @caughtexception;
r13 = $r4;
r5 = virtualinvoke r13.<java.lang.reflect.InvocationTargetException: java.lang.Throwable getTargetException()>();
$z0 = r5 instanceof java.lang.AbstractMethodError;
if $z0 != 0 goto (branch);
";
    "Block 4:
[preds: 3 ] [succs: 8 9 12 6 ]
goto [?= virtualinvoke r12.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, null)];
"->"Block 12:
[preds: 4 6 ] [succs: ]
$r2 := @caughtexception;
$r3 = new java.lang.RuntimeException;
specialinvoke $r3.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Test failed (Unexpected exception)\");
throw $r3;
";
    "Block 4:
[preds: 3 ] [succs: 8 9 12 6 ]
goto [?= virtualinvoke r12.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, null)];
"->"Block 6:
[preds: 4 ] [succs: 8 9 12 7 ]
virtualinvoke r12.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, null);
";
    "Block 6:
[preds: 4 ] [succs: 8 9 12 7 ]
virtualinvoke r12.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, null);
"->"Block 8:
[preds: 4 6 ] [succs: ]
$r7 := @caughtexception;
$r8 = new java.lang.RuntimeException;
specialinvoke $r8.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Test failed (AbstractMethodError passed through)\");
throw $r8;
";
    "Block 6:
[preds: 4 ] [succs: 8 9 12 7 ]
virtualinvoke r12.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, null);
"->"Block 9:
[preds: 4 6 ] [succs: 10 11 ]
$r4 := @caughtexception;
r13 = $r4;
r5 = virtualinvoke r13.<java.lang.reflect.InvocationTargetException: java.lang.Throwable getTargetException()>();
$z0 = r5 instanceof java.lang.AbstractMethodError;
if $z0 != 0 goto (branch);
";
    "Block 6:
[preds: 4 ] [succs: 8 9 12 7 ]
virtualinvoke r12.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, null);
"->"Block 12:
[preds: 4 6 ] [succs: ]
$r2 := @caughtexception;
$r3 = new java.lang.RuntimeException;
specialinvoke $r3.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Test failed (Unexpected exception)\");
throw $r3;
";
    "Block 6:
[preds: 4 ] [succs: 8 9 12 7 ]
virtualinvoke r12.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, null);
"->"Block 7:
[preds: 6 ] [succs: 13 ]
goto [?= return];
";
    "Block 7:
[preds: 6 ] [succs: 13 ]
goto [?= return];
"->"Block 13:
[preds: 7 11 ] [succs: ]
return;
";
    "Block 9:
[preds: 4 6 ] [succs: 10 11 ]
$r4 := @caughtexception;
r13 = $r4;
r5 = virtualinvoke r13.<java.lang.reflect.InvocationTargetException: java.lang.Throwable getTargetException()>();
$z0 = r5 instanceof java.lang.AbstractMethodError;
if $z0 != 0 goto (branch);
"->"Block 10:
[preds: 9 ] [succs: ]
$r6 = new java.lang.RuntimeException;
specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String)>(\"Test failed (InvocationTargetException didn\'t wrap AbstractMethodError)\");
throw $r6;
";
    "Block 9:
[preds: 4 6 ] [succs: 10 11 ]
$r4 := @caughtexception;
r13 = $r4;
r5 = virtualinvoke r13.<java.lang.reflect.InvocationTargetException: java.lang.Throwable getTargetException()>();
$z0 = r5 instanceof java.lang.AbstractMethodError;
if $z0 != 0 goto (branch);
"->"Block 11:
[preds: 9 ] [succs: 13 ]
goto [?= return];
";
    "Block 11:
[preds: 9 ] [succs: 13 ]
goto [?= return];
"->"Block 13:
[preds: 7 11 ] [succs: ]
return;
";
}
